language: ruby
sudo: false
branches:
  only:
    - master
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.7
  - ruby-head
  - rbx-3
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-head
