module Eqq
  interface _Patternable
    def ===: (untyped object) -> bool
  end

  interface _ToSym
    def to_sym: -> Symbol
  end

  interface _Inspectable
    def inspect: () -> String
  end

  module Buildable
    type patternable_lambda = ^(untyped object) -> bool
    type product = patternable_lambda & _Inspectable

    # A private constant. Should not be used in your code.
    ANYTHING: product

    # A private constant. Should not be used in your code.
    BOOLEAN: product

    # A private API. Should not be used in your code.
    def self.safe_inspect: (untyped object)-> String

    # A private API. Should not be used in your code.
    def self.set_inspect: (name: String, product: patternable_lambda, arguments: Array[untyped])-> void

    # A private API. Should not be used in your code.
    def self.validate_patterns: (*untyped) -> void

    extend Buildable
    def OR: (_Patternable, _Patternable, *_Patternable) -> product
    def AND: (_Patternable, _Patternable, *_Patternable) -> product
    def NAND: (_Patternable, _Patternable, *_Patternable) -> product
    def NOR: (_Patternable, _Patternable, *_Patternable) -> product
    def XOR: (_Patternable, _Patternable) -> product
    def NOT: (_Patternable) -> product
    def EQ: (untyped object) -> product
    def SAME: (untyped object) -> product
    def CAN: (_ToSym, *_ToSym) -> product
    def RESCUE: (Module, _Patternable) -> product
    def QUIET: (_Patternable, *_Patternable) -> product
    def SEND: (Symbol | String name, _Patternable) -> product
    def ANYTHING: () -> product
    def BOOLEAN: () -> product
  end

  extend Buildable

  class Error < StandardError
  end

  class InvalidProductError < Error
  end

  # A private API. Should not be used in your code.
  class DSLScope
    include Buildable
  end

  VERSION: String

  # A private constant. Should not be used in your code.
  INSPECTION_FALLBACK: String

  def self.valid?: (untyped object) -> bool
  def self.define:  { () -> _Patternable } -> _Patternable
end
