name: Signature
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test_signatures.yml'
      - 'lib/**'
      - 'exe/**'
      - '**.md'
      - '**.txt'
      - '**.gemspec'
      - 'Gemfile'
      - '.yardopts'
      - 'Rakefile'
  pull_request:
    paths:
      - '.github/workflows/test_signatures.yml'
      - 'lib/**'
      - 'exe/**'
      - '**.md'
      - '**.txt'
      - '**.gemspec'
      - 'Gemfile'
      - '.yardopts'
      - 'Rakefile'
jobs:
  validate_signatures:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake validate_signatures >/dev/null
