# https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: Test
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test_behaviors.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
  pull_request:
    paths:
      - '.github/workflows/test_behaviors.yml'
      - 'lib/**'
      - 'test/**'
      - 'spec/**'
      - '.rspec'
      - '**.gemspec'
      - 'Gemfile'
      - 'Rakefile'
jobs:
  test_behaviors:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [head, '3.3', '3.2']
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: development
    steps:
      - name: Install libyaml
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo apt-get install --no-install-recommends --assume-yes libyaml-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # Enabling is the recommended way, but it cannot detect runner changes in early stage.
          # So disable it is better for test job, do not mind in other jobs
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - run: bundle install
      - run: bundle exec rake test_behaviors --suppress-backtrace='\/bundle'
